/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMessageBox: typeof import('~icons/ep/message-box')['default']
    IEpReading: typeof import('~icons/ep/reading')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../components/mainbox/TheHeader.vue')['default']
    TheSideMenu: typeof import('./../components/mainbox/TheSideMenu.vue')['default']
  }
}
